name: Build and Test Spring Boot Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build Docker image
      run: docker build -t springboot-hello-app --build-arg SPRING_PROFILE=prod .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-container springboot-hello-app
        sleep 10
        curl http://localhost:8080/api/hello || exit 1